apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "torpeekerback:0.1"
          ports:
            - name: http
              containerPort: 8000
          resources:
            limits:
              cpu: 1
              memory: "256Mi"
