apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tor 
    spec:
      containers:
        - name: tor 
          image: 'torpeekertor:0.1'
          ports:
            - name: tcp
              containerPort: 9050
          resources:
            limits:
              cpu: 0.2
              memory: '128Mi'
